### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by PickleNik** [thisDOTname/vue-share-it#11]
app.use() ?

**Comment by KenEucker** [comment]
I was able to add this project to vue3 after adding a shim for it `declare module "vue-share-it"` and by fixing a key issue in the shareIt.vue template.

However, I still can't get this library to work in Vue3. I seem to be having issues with fontawesome and a component having undefined props:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'icon')
    at Proxy.render (index.es.js:434:26)
    at renderComponentRoot (runtime-core.esm-bundler.js:821:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5748:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5861:51)
    at setupRenderEffect (runtime-core.esm-bundler.js:5869:5)
    at mountComponent (runtime-core.esm-bundler.js:5659:5)
    at processComponent (runtime-core.esm-bundler.js:5612:9)
    at patch (runtime-core.esm-bundler.js:5087:11)
    at mountChildren (runtime-core.esm-bundler.js:5331:7)
```

Which occurs at this block from FontAwesomeIcon:

```
render: function render(createElement, context) {
    var props = context.props;
    var iconArgs = props.icon, <---- line it fails on
        maskArgs = props.mask,
        symbol = props.symbol,
        title = props.title;
```
